Eideticom/eid-hermes

- .github/workflows/reviewdog.yml
To enable some CI on the master branch add the ReviewDog GitHub
workflow. On the GitHub site we ensure all PRs to master pass this
workflow before they can be merged into master.
> reviewdog.yml: Add the reviewdog GitHub workflow

- README.md
eid-hermes should include a QEMU model and the Linux driver in
addition to the AWS F1 instance. Update the README to reflect this.
> README.md: Add reference to QEMU model and Linux driver

- specs/eid-hermes-interface.md
A draft of the specs used the term "program memory", but this was
abandoned in favour of "data slot". However, some references to the old
nomenclature remained, so we fix those.
> specs: Fix slots names

- README.md
Now we have made our fork of QEMU public [1] refer to this repo in the
README.md.
[1] https://github.com/Eideticom/eid-hermes-qemu
> eid-hermes-qemu: Add reference to the public fork of QEMU

- specs/eid-hermes-interface.md
From a discussion on [eid-hermes-qemu](https://github.com/Eideticom/eid-hermes-qemu/pull/4), a couple issues with our current interface became apparent:
- the interface version was too small (1 byte)
- the timestamp is not very useful
So we increase the interface version to 4 bytes and replace the timestamp with a wider register (48 bytes), which should be the "git describe" of qemu/fpga.
Increase the interface version to 2.
> specs: increase version size register + replace timestamp with git describe

- README.md
- ansible/ansible.cfg
- ansible/hermes.yml
- ansible/inventory
- ansible/roles/pcimem/tasks/main.yml
- ansible/roles/xdma/tasks/main.yml
- ansible/roles/xdma_test/files/xdma_test.c
- ansible/roles/xdma_test/tasks/main.yml
These ansible roles and playbook will install and test the xdma driver, patching it to work with the Hermes vendor ID/device ID.
It also installs [pcimem](https://github.com/billfarrow/pcimem), a tool to read/write BARs.
> Add ansible roles to setup xdma + pcimem

- specs/eid-hermes-commands-format.md
Users of Hermes devices communicate with the device through commands,
which are handled by a kernel driver.
Introduce some of the commands and their submission and completion entry
formats.
> specs: add commands format

- specs/eid-hermes-theory-of-operation.md
Non-DMA command requests/responses will be written to BAR0 registers, at
offsets TBD. This is similar to how XDMA operates.
When non-XDMA commands complete, the device will raise an interrupt.
> specs: add how commands requests/responses are sent to/from the device

- README.md
- tests/unit_test
These tests write to the device then read back and check if the data
matches.
Test different buffer sizes to exercise different paths on the device.
> unit_test: add XDMA tests

- specs/eid-hermes-interface.md
For every eBPF engine (EHENG), we have one set of command
request/response registers (starting at 0x1000) and one one-byte control
register (starting at 0x2000).
The user must write to the command request register, then write to the
corresponding control register, which starts the command. When the
command finishes, the hardware writes to the command response registers
and clears the control register.
Note that the above does not apply to the Write/Read commands, which are
handled by the hermes/xdma driver.
Fixes #16
> specs: add BAR0 register for command requests/responses

- examples/iovec.c
- src/driver/hermes_cdev.c
- src/driver/hermes_mod.h
- src/driver/libxdma.c
- src/driver/xdma_sgdma.c
- src/driver/xdma_sgdma.h
- tests/unit_test
As discussed on #19, this adds read_iter and write_iter, which support the use of the RWF_ flags, which we plan to use to trigger program execution. Currently, though, no such flags are supported and will be added on a future PR once the qemu device gets the eBPF engines (https://github.com/Eideticom/eid-hermes-qemu/issues/8).
> Add read_iter / write_iter 

- specs/eid-hermes-commands-format.md
- specs/eid-hermes-interface.md
- specs/eid-hermes-theory-of-operation.md
A couple of minor edits to the specs, adding a new command return code (invalid opcode) and a new register that shows when a command has completed.
> specs: add new status and register

- src/driver/hermes_cdev.c
- src/driver/hermes_mod.c
- src/driver/hermes_mod.h
- src/driver/xdma_sgdma.h
Use an IDA to keep track of which XDMA channels are being used. If there
are no idle channels, retry until one is available, or until a time
threshold is met, in which case the syscall will fail with EBUSY.
> driver: select an idle XDMA channel

- src/driver/libxdma.c
After we converted xdma_channel_read_write to work with iov_iter
(dc657952b146), the sg_table's orig_nents (the allocated size) can now be
larger than the mapped size (nents).
This was partially fixed on 5bf1f0df0689, but a couple of references to
orig_nents remained in the debug code (which was protected by #ifdef
macros and hence not included).
Fixes: dc657952b146 ("driver: convert xdma_channel_read_write to work
with iov_iter")
> driver: fix sg_table nents

- src/driver/hermes_mod.c
- src/driver/libxdma.c
- src/driver/libxdma.h
- src/driver/xdma_sgdma.c
- src/driver/xdma_sgdma.h
Continue cleaning up the XDMA driver by removing more unused code and reorganizing it a bit.
This PR depends on #26 and #27 and starts on d96057f ("driver: cleanup: remove remaining performance testing code"). I'll rebase when those get in.
> XDMA cleanup part 2

- README.md
- src/driver/hermes_mod.c
- src/driver/libxdma.c
- src/driver/libxdma.h
With #ifdef's for kernels 3.5, 3.16, 4.12, 4.13, the code was getting a
bit of maintenance pain. Popular distros (Ubuntu 18.04/20.04 and
CentOS/RHEL 8) already use kernels above 4.13, so the chance of those
macros being useful is diminished.
A notable exception is RHEL/CentOS 7, which is still on 3.10 and will
thus no longer be supported.
We keep only one LINUX_VERSION_CODE macro, for 5.1.0, as that is
required to support RHEL/CentOS 8.
> driver: drop support for older kernels

- src/driver/hermes_mod.c
- src/driver/libxdma.c
- src/driver/libxdma.h
PR #23 requires setting up interrupts for the eBPF engines. However, the XDMA and interrupt setup/teardown were tied together, so adding the eBPF interrupts would have been awkward/hacky.
This PR cleans that up by moving all the interrupt setup/teardown out of XDMA functions and files into hermes_mod.c.
> Split XDMA and interrupt setup/teardown

- specs/eid-hermes-commands-format.md
The Hermes spec does not have an response code to indicate that the command opcode is not 0x00, 0x01, 0x80. Allocating 0x06 for that.
> commands: add response code for invalid opcode

- specs/eid-hermes-interface.md
Instead of using a single byte for EHCMDCTRL and giving each bit a
different meaning, just make that register wider so that each
sub-register can take a full byte.
> specs: Increase EHCMDCTRL size

- src/driver/hermes_mod.c
On 5.7+ kernels, the pci_cleanup_aer_uncorrect_error_status() function
was renamed to pci_aer_clear_nonfatal_status(). Upstream commit:
https://github.com/torvalds/linux/commit/894020fdd88c1e9a74c60b67c0f19f1c7696ba2f
Reported-by: Niclas Hedam <nhed@itu.dk>
> driver: fix to work on 5.7+ kernels

- specs/eid-hermes-commands-format.md
An eBPF program can use just part of a program slot and the eBPF engine
currently has no way of knowing its length.
This can be a problem if, for example, the eBPF engine tries to validate
if a program is valid. For example, in uBPF, the [validate()
function][1] needs the number of instructions in the program.
A simple solution is to add the program length to the command request.
An alternative would be to modify the XDMA engine to store the program
length if it the XDMA target address is in a program slot, but this
would be much more complicated.
[1]: https://github.com/iovisor/ubpf/blob/0014f298be3e2a636fd6243908238fb027527e28/vm/ubpf_vm.c#L566
> specs: include program length on command request
